### ISSUE TITLE
Registration: Form Type

### ISSUE THREAD

**Issue by ad-olfo** [SwampTeam/letzswap#1]
Branch: `registration`

> ## This task is about creating the registration form for new users

### To complete this task you need to:

- [x] Create a  registration form (`php bin/console make:registration-form`) with the builder and name it `RegistrationFormType`

- [x] include all the needed fields in the formBuilder

**Comment by marcolabreu** [comment]
### Roles 
User role should be automatically assigned.
### Admin role
How to assign admin role?
