### ISSUE TITLE
Database: Entities

### ISSUE THREAD

**Issue by ad-olfo** [SwampTeam/letzswap#14]
> ## This task is about creating the whole database for the project

### To complete this task you need to:

- [x] Create the database `letzswap` with the cmd `php bin/console doctrine:database:create`

- [x] Create the following entities with Doctrine: 

- `users`with `php bin/console make:user` (don't use Argon2i)

- `items` with `php bin/console make:entity`

- `image` with `php bin/console make:entity`

- `categories` with `php bin/console make:entity`

- [x] Add the Setters and Getters

- [x] Add the annotations

- [x] Validate the mappings with `php bin/console doctrine:schema:validate`

- [x] Generate the migration script `php bin/console doctrine:migrations:diff`

- [x] Migrate `php bin/console doctrine:migrations:migrate`

**Comment by 41646F6C666F** [comment]
Database has 6 tables: user, item, picture, item_status, user_status, status
