### ISSUE TITLE
Crashes when user not logged in

### ISSUE THREAD

**Issue by marcolabreu** [SwampTeam/letzswap#67]
- [x] Made a redirect to regsiter when user clicks on letzswap in the item detials

**Comment by ad-olfo** [comment]
When and Where this occur?

**Comment by KarloC23** [comment]
When unauthenticated user, clicks on letzswap, website crashes.

**Comment by KarloC23** [comment]
I will (try to)  fix the issue by creating a redirect to register when unauthenticated user, clicks on the letzswap, and also add a button to log in in case it is an already existing user but he just forgot to log in
